apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
      - name: conversao-temperatura
        image: marjorie02/guia-jenkins:teste
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: conversao-temperatura
  type: NodePort
  ports:
  - port: 80          # porta do serviço no cluster
    targetPort: 8080  # porta que o container está escutando
    nodePort: 9090    # porta externa no node para acesso
