apiVersion: apps/v1
kind: Deployment
metadata:
  name: guia-jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guia-jenkins
  template:
    metadata:
      labels:
        app: guia-jenkins
    spec:
      containers:
      - name: guia-jenkins
        image: marjorietalberg/guia-jenkins:{{tag}}
        ports:
        - containerPort: 8080
